title: CSharpCooking
author: Ruslan Gibadullin
email: landwatersun@gmail.com
description: Рецепты вкусных программ на языке C# 
show_excerpts: true
# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
plainwhite:
  name: Рецепты на языке C#
  #tagline: Рецепты на языке C#
  sitemap: true # set to true to generate sitemap.xml content
  search: true # set to true to enable searchbar
  disqus_shortname: csharpcooking
  dark_mode: true # set to true to add dark mode toggle
  portfolio_image: "assets/portfolio.svg" # the path from the base directory of the site to the image to display (no / at the start)
  html_lang: "ru" # set the lang attribute of the <html> tag for the pages. See here for a list of codes: https://www.w3schools.com/tags/ref_country_codes.asp
  condensed_mobile:
    #- home
    - page
    - post
  navigation:
    - title: Главная
      url: "/"
    - title: Учебные курсы
      url: "/courses"
    - title: Источники
      url: "/sources"
  social_links:
    youtube: CSharpCooking
    #twitter: samarsault
    github:  CSharpCooking
    #linkedIn: in/samarsault
    #rss: rss
    #dribbble: jekyll
    #flickr:   jekyll    
    #instagram: CSharpCooking
    #pinterest: jekyll
    #facebook: rfgibadullin
    #soundcloud: jekyll
    telegram: CSharpCooking
    #gitlab: jekyll
    email: CSharpCooking@gmail.com

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md
plugins:
  - jekyll-seo-tag
  - jekyll-feed